export type ProjectLink = {
  label: string;
  href: string;
  kind: 'github' | 'live' | 'docs';
};

export type Project = {
  slug: string;
  name: string;
  category: string;
  year: string;
  tagline: string;          // one-line description
  problem: string;
  solution: string;
  architecture: string;
  results: string[];
  tech: string[];
  links: ProjectLink[];
  /** Tier:
   *   'flagship' — featured case study on homepage
   *   'secondary' — More Work list
   */
  tier: 'flagship' | 'secondary';
  /** Visual identity used to render an editorial project plate */
  visual: {
    /** A single ASCII glyph / monogram */
    glyph: string;
    /** Accent tone for the plate (still restrained) */
    tone: 'ink' | 'accent' | 'neutral';
  };
};

/**
 * Curated, source-of-truth project set.
 * Order within each tier matters — it is the displayed order.
 */
export const projects: Project[] = [
  // ---------------------- Flagship (8) ----------------------
  {
    slug: 'attestguard',
    name: 'AttestGuard',
    category: 'Cybersecurity · Kubernetes',
    year: '2025',
    tagline: 'Zero-trust supply-chain security for Kubernetes.',
    problem:
      'Container images ship without verifiable provenance, and runtime threats are typically detected only after damage. Teams lack a single pipeline that prevents vulnerable artifacts from being deployed and isolates compromised workloads in real time.',
    solution:
      'A complete supply-chain security platform: SBOM generation, Trivy vulnerability gating, Sigstore Cosign OIDC keyless signing, SLSA Level 3 provenance, and Falco eBPF runtime threat containment with automatic pod isolation.',
    architecture:
      'Admission-time enforcement via OPA Rego policies gates deployments on signed, SBOM-bearing, vulnerability-cleared images. At runtime, Falco eBPF rules trigger a containment controller that quarantines pods within 538 ms while preserving forensic state. Provenance and signatures are attested using Sigstore Cosign and verified against SLSA Level 3 requirements.',
    results: [
      '100% True Positive Rate, 0% False Positive Rate across the eval corpus',
      '4 ms Mean Time To Detect at runtime',
      '538 ms Mean Time To Respond — automatic pod isolation',
      '11 / 11 OPA Rego policies passing',
    ],
    tech: ['Python', 'Go', 'Kubernetes', 'Falco eBPF', 'Sigstore Cosign', 'OPA'],
    links: [
      { label: 'GitHub', href: 'https://github.com/unveiledhistory49/attestguard', kind: 'github' },
    ],
    tier: 'flagship',
    visual: { glyph: 'AG', tone: 'ink' },
  },
  {
    slug: 'lendx-protocol',
    name: 'LendX Protocol',
    category: 'DeFi · Lending Protocol',
    year: '2025',
    tagline: 'Aave / Compound–inspired money market, production-grade.',
    problem:
      'Public lending-protocol forks ship with shallow liquidation logic, brittle interest accounting, and oracle assumptions that fail in stress. Without invariant testing, edge-case exploits remain latent.',
    solution:
      'A complete lending and borrowing protocol: scaled-balance interest, tiered liquidation engine, flash loans, Chainlink price feeds, and 500+ invariant fuzz runs to harden state-machine safety.',
    architecture:
      'Implements the Aave v2-style scaled-balance interest model for high-precision compounding. Liquidation uses a tiered close-factor model with health-factor thresholds. Flash loans atomically borrow-repay within a single transaction. Property-based fuzzing with Foundry exercises invariants across borrow / repay / liquidate paths.',
    results: [
      '500+ Foundry invariant fuzz runs passing',
      'Scaled-balance interest accounting with full decimal precision',
      'Tiered liquidation engine with Chainlink price-feed integration',
      'Deployed on Ethereum Sepolia and Base Sepolia',
    ],
    tech: ['Solidity', 'Foundry', 'Chainlink', 'TypeScript'],
    links: [
      { label: 'GitHub', href: 'https://github.com/unveiledhistory49/LendX', kind: 'github' },
    ],
    tier: 'flagship',
    visual: { glyph: 'LX', tone: 'accent' },
  },
  {
    slug: 'secureloop',
    name: 'SecureLoop',
    category: 'DevSecOps · SOAR',
    year: '2025',
    tagline: 'Closed-loop security bridging AppSec and SOC.',
    problem:
      'Findings generated by AppSec rarely translate into SOC detections, and SOC incidents rarely feed back into pre-merge controls. The two halves of security operate in isolation.',
    solution:
      'A SOAR platform where production attacks trigger automated containment, Merkle-tree audit logging, and dynamic Semgrep/Nuclei rule synthesis auto-committed back into CI/CD — a true security feedback loop.',
    architecture:
      'Detections fan out to an OPA policy engine and an OpenTelemetry pipeline. Containment actions are executed through a reversible playbook layer with human-in-the-loop checkpoints. Rule synthesis uses Semgrep AST and Nuclei templates, with changes gated through CI and committed via signed GitOps commits. Every event is appended to a hash-chained Merkle audit log.',
    results: [
      '100% True Positive Rate in evaluation',
      '0.24 ms Mean Time To Detect',
      '19 closed feedback cycles from incident to rule',
      'Maps 7 / 7 OWASP and MITRE ATT&CK vectors',
    ],
    tech: ['TypeScript', 'Python', 'OPA', 'Semgrep', 'Nuclei', 'OpenTelemetry'],
    links: [
      { label: 'GitHub', href: 'https://github.com/unveiledhistory49/secureloop', kind: 'github' },
    ],
    tier: 'flagship',
    visual: { glyph: 'SL', tone: 'ink' },
  },
  {
    slug: 'gatekeeper',
    name: 'Gatekeeper',
    category: 'Identity · IAM · Go',
    year: '2025',
    tagline: 'Workforce IAM with hash-chained auditability.',
    problem:
      'Most workforce IAM stacks leak privileges through API keys, lose auditability under incident response, and offer no enforced path to revoke lingering access.',
    solution:
      'A purpose-built Go IAM service: users, RBAC roles, API keys, sessions, OIDC SSO, access-review campaigns with enforced revocation, and a hash-chained tamper-evident audit log.',
    architecture:
      'Go 1.23 with the chi router for a clean HTTP layer. Argon2id password hashing. API keys are deliberately constructed so they cannot satisfy RBAC checks — a small but important structural safety property. SCIM provisioning for directory sync. The audit log is a hash chain where each entry references the previous, so any tamper is detectable.',
    results: [
      'Argon2id password hashing with secure parameters',
      'Hash-chained, tamper-evident audit log',
      'API keys structurally prevented from satisfying RBAC checks',
      'SCIM provisioning + OIDC SSO + access-review campaigns',
    ],
    tech: ['Go 1.23', 'chi', 'SQLite / Postgres', 'Docker', 'OIDC', 'SCIM', 'Argon2id', 'RBAC'],
    links: [
      { label: 'GitHub', href: 'https://github.com/unveiledhistory49/gatekeeper', kind: 'github' },
    ],
    tier: 'flagship',
    visual: { glyph: 'GK', tone: 'ink' },
  },
  {
    slug: 'omniyield',
    name: 'OmniYield',
    category: 'DeFi · Cross-Chain',
    year: '2025',
    tagline: 'Cross-chain yield aggregator across Base and Solana.',
    problem:
      'Yield lives in fragmented vaults on fragmented chains. Users pay gas on entry, monitor positions manually, and lose yield to idle balances.',
    solution:
      'ERC-4626 auto-compounding vaults with gasless deposits via Pimlico (ERC-4337 Account Abstraction) and deBridge cross-chain bridging — one route, no manual gas.',
    architecture:
      'Vaults are ERC-4626 compliant for composability. Deposits are gasless thanks to a Pimlico-sponsored UserOperation path under ERC-4337. Bridging uses deBridge for cross-chain settlement. The front end is a Next.js 16 dashboard using wagmi for wallet integration.',
    results: [
      'ERC-4626 auto-compounding vaults on Base and Solana',
      'Gasless deposits via ERC-4337 / Pimlico',
      'deBridge cross-chain settlement',
      '37 / 37 smart-contract tests passing',
    ],
    tech: ['Solidity', 'Next.js 16', 'wagmi', 'Pimlico', 'deBridge'],
    links: [
      { label: 'GitHub', href: 'https://github.com/unveiledhistory49/OmniYield', kind: 'github' },
    ],
    tier: 'flagship',
    visual: { glyph: 'OY', tone: 'accent' },
  },
  {
    slug: 'agentic',
    name: 'Agentic',
    category: 'AI / ML · Multi-Agent',
    year: '2025',
    tagline: 'A pure-Python multi-agent platform for constrained hardware.',
    problem:
      'Multi-agent systems typically require heavyweight runtimes and paid APIs. Building one that runs well on a laptop — with real long-term memory and external tool integration — is a different problem.',
    solution:
      'A lightweight multi-agent platform with dynamic model switching via NVIDIA NIM, conversation threading, long-term agent memory, file-system integration, and MCP server connections to GitHub, Vercel, Supabase, and Playwright.',
    architecture:
      'Pure Python with Flask for transport. Agents are routed through an abstraction layer that hot-swaps underlying models against the NVIDIA NIM API without code changes. MCP (Model Context Protocol) servers connect the agent to real-world tools. Memory is persistent and keyed by conversation thread.',
    results: [
      'Pure-Python, no heavy framework dependencies',
      'Dynamic model switching via NVIDIA NIM',
      'Long-term agent memory keyed by conversation thread',
      'MCP integrations: GitHub, Vercel, Supabase, Playwright',
    ],
    tech: ['Python', 'Flask', 'NVIDIA NIM API', 'SQLite', 'MCP'],
    links: [
      { label: 'GitHub', href: 'https://github.com/eaglefavor/Agentic', kind: 'github' },
    ],
    tier: 'flagship',
    visual: { glyph: 'AI', tone: 'ink' },
  },
  {
    slug: 'evalforge',
    name: 'EvalForge',
    category: 'AI / ML · Evaluation',
    year: '2025',
    tagline: 'Reproducible ML evaluation, no framework lock-in.',
    problem:
      'Most ML evaluations are quietly non-reproducible: floating-point order differs across machines, datasets are silently mutated, and CI gates pass on runs that should fail.',
    solution:
      'A reproducible evaluation framework: pinned seeds with SHA-256 stream derivation, content-hashed datasets, digest-verified runs, and CI quality gates. Models are plain callables — no PyTorch / TensorFlow dependency.',
    architecture:
      'Statistical primitives are implemented from scratch on numpy: bootstrap confidence intervals, exact McNemar test, pass@k. Determinism is enforced by deriving PRNG streams from a content-hashed seed and dataset digest. The run registry is SQLite, and CI gates run against digest-verified baselines.',
    results: [
      'Content-hashed datasets with SHA-256 stream-derived seeds',
      'Digest-verified run registry for true reproducibility',
      'Bootstrap CIs, exact McNemar, pass@k from scratch on numpy',
      '28 tests + CI quality gates',
    ],
    tech: ['Python', 'numpy', 'Docker', 'CI Gates'],
    links: [
      { label: 'GitHub', href: 'https://github.com/unveiledhistory49/evalforge', kind: 'github' },
    ],
    tier: 'flagship',
    visual: { glyph: 'EF', tone: 'accent' },
  },
  {
    slug: 'presensys',
    name: 'Presensys',
    category: 'EdTech · PWA',
    year: '2024',
    tagline: 'University attendance management — offline-first.',
    problem:
      'University attendance systems break down exactly when they matter most: on patchy campus Wi-Fi, with hundreds of students scanning in at the same minute, under the burden of access-control and auditability requirements.',
    solution:
      'An offline-first PWA built on React 19 with a Gemini 1.5 Flash NLP command bar, biometric authorisation, role-based access, and a service worker that pre-caches 34 entries for fast cold starts.',
    architecture:
      'React 19 + TypeScript front end. Supabase for auth, Postgres, and row-level security. Gemini 1.5 Flash powers an NLP command bar that resolves natural-language queries against the attendance domain. The service worker pre-caches critical routes and assets, so the app boots and remains interactive on flaky networks.',
    results: [
      '377 commits of active development',
      '34 pre-cached entries in the service worker for offline-first use',
      'NLP command bar powered by Gemini 1.5 Flash',
      'Biometric data authorisation with role-based access',
    ],
    tech: ['React 19', 'TypeScript', 'Supabase', 'Gemini 1.5 Flash'],
    links: [
      { label: 'Live', href: 'https://presensys.vercel.app', kind: 'live' },
    ],
    tier: 'flagship',
    visual: { glyph: 'PS', tone: 'ink' },
  },

  // ---------------------- Secondary (More Work) ----------------------
  {
    slug: 'coldchain',
    name: 'ColdChain',
    category: 'IoT · Compliance',
    year: '2024',
    tagline: 'Immutable IoT telemetry for temperature-sensitive supply chains.',
    problem:
      'Pharmaceutical and biologic supply chains need audit-grade IoT telemetry — append-only readings, excursion budgets, calibration tracking — with e-signatures that hold up to scrutiny.',
    solution:
      'Write-once immutable readings, MKT per USP <1079>, calibration coverage, Part-11-style e-signatures on content hashes, and HMAC-signed webhook outbox.',
    architecture:
      'FastAPI with SQLAlchemy. Storage is append-only; nothing is updated, only corrected via reversal records. Excursion budgets track cumulative temperature drift. E-signatures hash the content they attest to, then sign the hash. The webhook outbox is HMAC-signed for downstream verification.',
    results: [
      'Append-only write-once telemetry — quarantine-never-drop posture',
      'MKT (Mean Kinetic Temperature) per USP <1079>',
      'Part-11-style e-signatures on content hashes',
      'HMAC-signed webhook outbox for downstream verification',
    ],
    tech: ['Python', 'FastAPI', 'SQLAlchemy', 'Docker Compose', 'IoT'],
    links: [
      { label: 'GitHub', href: 'https://github.com/unveiledhistory49/coldchain', kind: 'github' },
    ],
    tier: 'secondary',
    visual: { glyph: 'CC', tone: 'ink' },
  },
  {
    slug: 'ledgerline',
    name: 'LedgerLine',
    category: 'FinTech · Accounting',
    year: '2024',
    tagline: 'Append-only double-entry ledger with idempotent APIs.',
    problem:
      'Most accounting systems treat the ledger as mutable, which makes restatement unreliable and external integrations unsafe.',
    solution:
      'Double-entry ledger with append-only, idempotent HTTP API. Balanced journals, multi-currency with integer minor units, append-only reversals, period close with trial-balance hash snapshots.',
    architecture:
      'FastAPI + SQLAlchemy. Every journal is balanced at write time. Currencies are tracked as integer minor units. Period close produces a hash snapshot of the trial balance. Webhooks are signed and idempotent at the receiver.',
    results: [
      'Idempotent HTTP API for safe retries',
      'Multi-currency with integer minor units (no float drift)',
      'Append-only reversals — never destructive edits',
      'Trial balance, balance sheet, and income statement reports',
    ],
    tech: ['Python', 'FastAPI', 'SQLAlchemy', 'Docker'],
    links: [
      { label: 'GitHub', href: 'https://github.com/unveiledhistory49/ledgerline', kind: 'github' },
    ],
    tier: 'secondary',
    visual: { glyph: 'LL', tone: 'accent' },
  },
  {
    slug: 'aa-multichain-wallet',
    name: 'AA Multichain Wallet',
    category: 'Web3 · Account Abstraction',
    year: '2024',
    tagline: 'EVM + Solana wallet with gasless transactions.',
    problem:
      'Multichain wallets tend to be either EVM-first or Solana-first. A genuinely unified UX with gasless transactions, staking, and a Solana program layer is rare.',
    solution:
      'A production-ready multichain wallet: ERC-4337 gasless transactions, real-time portfolio analytics, staking vaults, and Solana Anchor programs. Turborepo monorepo with a security audit included.',
    architecture:
      'Turborepo monorepo. Next.js for the dashboard. Solidity contracts for EVM-side accounts and staking. Rust / Anchor for the Solana programs. Pimlico for ERC-4337 paymasters. Internal security audit documents the trust model.',
    results: [
      'EVM + Solana in a single dashboard',
      'ERC-4337 gasless transactions across chains',
      'Staking vaults + real-time portfolio analytics',
      'Includes internal security audit',
    ],
    tech: ['TypeScript', 'Solidity', 'Rust / Anchor', 'Pimlico'],
    links: [
      { label: 'GitHub', href: 'https://github.com/charlie0x-sol/aa-multichain-wallet', kind: 'github' },
    ],
    tier: 'secondary',
    visual: { glyph: 'AA', tone: 'ink' },
  },
  {
    slug: 'solana-paymaster',
    name: 'Solana Paymaster',
    category: 'Solana · Infrastructure',
    year: '2024',
    tagline: 'Gasless Solana transactions, congestion-aware.',
    problem:
      'End users should not need SOL just to use an app. A gasless relayer must be secure, rate-limited, and resilient to network congestion.',
    solution:
      'A Solana gasless transaction relayer: JWT challenge-response auth, rules engine, key rotation, IP rate limiting, Prometheus metrics, and aggressive rebroadcast every 2s for congestion resilience.',
    architecture:
      'TypeScript on Node.js with Redis for rate-limit state. JWT challenge-response gates every sponsored transaction. The rules engine enforces spend policies. Rebroadcast logic handles congestion. Prometheus metrics expose sponsorship volume, failure modes, and latency.',
    results: [
      'JWT challenge-response authentication',
      'Redis-backed IP rate limiting',
      'Aggressive rebroadcast every 2 s for congestion resilience',
      'Key rotation + Prometheus observability',
    ],
    tech: ['TypeScript', 'Node.js', 'Redis', 'Solana'],
    links: [
      { label: 'GitHub', href: 'https://github.com/charlie0x-sol/Paymaster', kind: 'github' },
    ],
    tier: 'secondary',
    visual: { glyph: 'SP', tone: 'accent' },
  },
  {
    slug: 'helios-solana',
    name: 'Helios-Solana',
    category: 'Solana · Monitoring',
    year: '2024',
    tagline: 'On-chain event stream at 1,400+ events / sec.',
    problem:
      'Raw Solana on-chain events are high-throughput and unstructured. Routing them to downstream systems requires decoding, filtering, and durable persistence.',
    solution:
      'A real-time monitoring pipeline processing 1,400+ events/sec with Anchor/Borsh decoding, batched webhooks, JSON Logic rule-based filtering, WASM transformer plugins, and Prometheus observability.',
    architecture:
      'TypeScript orchestrator with a Rust core for hot-path decoding. SQLite WAL provides durable event persistence. WASM plugins extend the transformer pipeline without redeploys. JSON Logic rules drive per-program filtering.',
    results: [
      '1,400+ events / sec sustained throughput',
      'Anchor / Borsh decoding into typed events',
      'WASM transformer plugins — extensible without redeploy',
      'SQLite WAL for durable event persistence',
    ],
    tech: ['TypeScript', 'Rust / WASM', 'Solana', 'Docker'],
    links: [
      { label: 'GitHub', href: 'https://github.com/charlie0x-sol/Helios-Solana', kind: 'github' },
    ],
    tier: 'secondary',
    visual: { glyph: 'HE', tone: 'ink' },
  },
  {
    slug: 'rpc-cacheflow',
    name: 'RPC-CacheFlow',
    category: 'Blockchain · DevOps',
    year: '2024',
    tagline: 'Enterprise-grade RPC proxy with intelligent caching.',
    problem:
      'Public RPC endpoints are flaky and expensive. Naive caching is unsafe because stale state produces broken transactions.',
    solution:
      'An RPC proxy gateway: intelligent caching, WebSocket multiplexing, P2C smart load balancing, Redis rate limiting, Prometheus metrics, and a Next.js admin dashboard.',
    architecture:
      'TypeScript core with Redis for cache + rate-limit state. Power-of-two-choices load balancing across upstream RPC providers. Helm chart for Kubernetes deployment. Grafana-ready Prometheus metrics. Admin dashboard in Next.js.',
    results: [
      'Power-of-two-choices load balancing across upstreams',
      'Redis-backed intelligent cache + rate limiting',
      'Kubernetes Helm chart for production deployment',
      'Next.js admin dashboard with Prometheus metrics',
    ],
    tech: ['TypeScript', 'Redis', 'Kubernetes', 'Helm', 'Prometheus'],
    links: [
      { label: 'GitHub', href: 'https://github.com/charlie0x-sol/RPC-CacheFlow', kind: 'github' },
    ],
    tier: 'secondary',
    visual: { glyph: 'RC', tone: 'accent' },
  },
  {
    slug: 'novacommerce',
    name: 'NovaCommerce',
    category: 'E-Commerce',
    year: '2024',
    tagline: 'Full-featured storefront, modern commerce UX.',
    problem:
      'A production-grade storefront needs a real catalog, cart, and checkout — not a marketing demo.',
    solution:
      'A live e-commerce storefront with a real product catalog, cart, and checkout flow, shipped on Next.js + Vercel.',
    architecture: 'Next.js on Vercel. Product catalog, cart state, and checkout flow integrated end-to-end. Clean, high-performance UI focused on conversion.',
    results: [
      'Live storefront with full catalog → cart → checkout flow',
      'Production deployment on Vercel',
      'High-performance, clean commerce UI',
    ],
    tech: ['Next.js', 'Vercel'],
    links: [
      { label: 'Live', href: 'https://novacommerce-store.vercel.app', kind: 'live' },
    ],
    tier: 'secondary',
    visual: { glyph: 'NV', tone: 'ink' },
  },
  {
    slug: 'lumen-systems',
    name: 'Lumen Systems',
    category: 'Dashboard · Systems',
    year: '2024',
    tagline: 'Infrastructure visibility and operational tooling.',
    problem:
      'Internal tooling often means either a fragile Grafana instance or a custom dashboard nobody owns.',
    solution:
      'A clean, production-ready dashboard platform built for infrastructure visibility and operational workflows.',
    architecture: 'Next.js on Vercel. Built for infrastructure-visibility use cases and operational tooling.',
    results: ['Live on Vercel', 'Production-ready interface'],
    tech: ['Next.js', 'Vercel'],
    links: [
      { label: 'Live', href: 'https://lumen-systems.vercel.app', kind: 'live' },
    ],
    tier: 'secondary',
    visual: { glyph: 'LM', tone: 'ink' },
  },
  {
    slug: 'frame-workflow',
    name: 'Frame Workflow',
    category: 'Productivity · Workflow',
    year: '2024',
    tagline: 'Visual pipeline for complex multi-step processes.',
    problem:
      'Multi-step creative and operational workflows need a visual surface, not a checklist.',
    solution:
      'A frame-by-frame workflow tool with an intuitive UI for managing complex multi-step pipelines.',
    architecture: 'React on Vercel. Frame-based state model with a visual pipeline.',
    results: ['Live on Vercel', 'Visual multi-step workflow UI'],
    tech: ['React', 'Vercel'],
    links: [
      { label: 'Live', href: 'https://frame-workflow.vercel.app', kind: 'live' },
    ],
    tier: 'secondary',
    visual: { glyph: 'FW', tone: 'accent' },
  },
  {
    slug: 'normal-tools',
    name: 'Normal Tools',
    category: 'Developer · Tools',
    year: '2024',
    tagline: 'Everyday utilities in a single fast interface.',
    problem:
      'Engineers reach for the same handful of utilities constantly — formatters, converters, generators, validators.',
    solution:
      'A toolbox of everyday web tools packaged into a single fast, no-friction interface.',
    architecture: 'Vanilla JavaScript on Vercel. Optimised for fast, no-install use.',
    results: ['Live on Vercel', 'Curated set of everyday utilities'],
    tech: ['JavaScript', 'Vercel'],
    links: [
      { label: 'Live', href: 'https://normal-tools.vercel.app', kind: 'live' },
    ],
    tier: 'secondary',
    visual: { glyph: 'NT', tone: 'ink' },
  },
  {
    slug: 'vigil',
    name: 'Vigil',
    category: 'Observability · Monitoring',
    year: '2024',
    tagline: 'Real-time system monitoring and alerting.',
    problem:
      'Incident response starts with awareness — most teams only discover problems from a customer.',
    solution:
      'A monitoring and alerting platform with configurable thresholds, status tracking, and a clean dashboard.',
    architecture: 'React on Vercel. Configurable alert thresholds, status tracking, and a dashboard built around incident clarity.',
    results: ['Live on Vercel', 'Configurable alerts and status tracking'],
    tech: ['React', 'Vercel'],
    links: [
      { label: 'Live', href: 'https://vigil-tawny-xi.vercel.app', kind: 'live' },
    ],
    tier: 'secondary',
    visual: { glyph: 'VG', tone: 'ink' },
  },
  {
    slug: 'numera-finance',
    name: 'Numera Finance',
    category: 'FinTech · Invoicing',
    year: '2024',
    tagline: 'Branded invoices, secure payment collection.',
    problem:
      'Freelancers and small firms need branded invoices and a real payment flow — not a spreadsheet.',
    solution:
      'A platform that dynamically renders branded invoices, calculates due dates, and routes clients to a secure Flutterwave payment gateway.',
    architecture: 'Python / Flask API backend. Front-end renders branded invoice templates. Flutterwave handles payment collection.',
    results: [
      'Dynamic branded invoice rendering',
      'Secure Flutterwave payment gateway integration',
      'Due-date calculation built in',
    ],
    tech: ['HTML / CSS / JS', 'Python', 'Flask', 'Vercel'],
    links: [
      { label: 'Live', href: 'https://numera-orcin.vercel.app', kind: 'live' },
    ],
    tier: 'secondary',
    visual: { glyph: 'NF', tone: 'accent' },
  },
];

export const flagshipProjects = projects.filter((p) => p.tier === 'flagship');
export const secondaryProjects = projects.filter((p) => p.tier === 'secondary');

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}
